//
// Created by cenka on 3/7/2024.
//

#ifndef INPUT_RECORDER_KEYS_HPP
#define INPUT_RECORDER_KEYS_HPP

#include "../stdafx.h"

namespace VirtualKeys
{
    constexpr const char* LMB = "VK_LBUTTON";
    constexpr const char* RMB = "VK_RBUTTON";
    constexpr const char* Cancel = "VK_CANCEL";
    constexpr const char* MMB = "VK_MBUTTON";
    constexpr const char* XButton1 = "VK_XBUTTON1";
    constexpr const char* XButton2 = "VK_XBUTTON2";
    constexpr const char* Back = "VK_BACK";
    constexpr const char* Tab = "VK_TAB";
    constexpr const char* Clear = "VK_CLEAR";
    constexpr const char* Return = "VK_RETURN";
    constexpr const char* Shift = "VK_SHIFT";
    constexpr const char* Control = "VK_CONTROL";
    constexpr const char* Menu = "VK_MENU";
    constexpr const char* Pause = "VK_PAUSE";
    constexpr const char* CapsLock = "VK_CAPITAL";
    constexpr const char* Escape = "VK_ESCAPE";
    constexpr const char* Space = "VK_SPACE";
    constexpr const char* PageUp = "VK_PRIOR";
    constexpr const char* PageDown = "VK_NEXT";
    constexpr const char* End = "VK_END";
    constexpr const char* Home = "VK_HOME";
    constexpr const char* Left = "VK_LEFT";
    constexpr const char* Up = "VK_UP";
    constexpr const char* Right = "VK_RIGHT";
    constexpr const char* Down = "VK_DOWN";
    constexpr const char* Select = "VK_SELECT";
    constexpr const char* Print = "VK_PRINT";
    constexpr const char* Execute = "VK_EXECUTE";
    constexpr const char* Snapshot = "VK_SNAPSHOT";
    constexpr const char* Insert = "VK_INSERT";
    constexpr const char* Delete = "VK_DELETE";
    constexpr const char* Help = "VK_HELP";
    constexpr const char* Zero = "0x30";
    constexpr const char* One = "0x31";
    constexpr const char* Two = "0x32";
    constexpr const char* Three = "0x33";
    constexpr const char* Four = "0x34";
    constexpr const char* Five = "0x35";
    constexpr const char* Six = "0x36";
    constexpr const char* Seven = "0x37";
    constexpr const char* Eight = "0x38";
    constexpr const char* Nine = "0x39";
    constexpr const char* A = "0x41";
    constexpr const char* B = "0x42";
    constexpr const char* C = "0x43";
    constexpr const char* D = "0x44";
    constexpr const char* E = "0x45";
    constexpr const char* F = "0x46";
    constexpr const char* G = "0x47";
    constexpr const char* H = "0x48";
    constexpr const char* I = "0x49";
    constexpr const char* J = "0x4A";
    constexpr const char* K = "0x4B";
    constexpr const char* L = "0x4C";
    constexpr const char* M = "0x4D";
    constexpr const char* N = "0x4E";
    constexpr const char* O = "0x4F";
    constexpr const char* P = "0x50";
    constexpr const char* Q = "0x51";
    constexpr const char* R = "0x52";
    constexpr const char* S = "0x53";
    constexpr const char* T = "0x54";
    constexpr const char* U = "0x55";
    constexpr const char* V = "0x56";
    constexpr const char* W = "0x57";
    constexpr const char* X = "0x58";
    constexpr const char* Y = "0x59";
    constexpr const char* Z = "0x5A";
    constexpr const char* LWin = "VK_LWIN";
    constexpr const char* RWin = "VK_RWIN";
    constexpr const char* Apps = "VK_APPS";
    constexpr const char* Sleep = "VK_SLEEP";
    constexpr const char* NumPad0 = "VK_NUMPAD0";
    constexpr const char* NumPad1 = "VK_NUMPAD1";
    constexpr const char* NumPad2 = "VK_NUMPAD2";
    constexpr const char* NumPad3 = "VK_NUMPAD3";
    constexpr const char* NumPad4 = "VK_NUMPAD4";
    constexpr const char* NumPad5 = "VK_NUMPAD5";
    constexpr const char* NumPad6 = "VK_NUMPAD6";
    constexpr const char* NumPad7 = "VK_NUMPAD7";
    constexpr const char* NumPad8 = "VK_NUMPAD8";
    constexpr const char* NumPad9 = "VK_NUMPAD9";
    constexpr const char* Multiply = "VK_MULTIPLY";
    constexpr const char* Add = "VK_ADD";
    constexpr const char* Separator = "VK_SEPARATOR";
    constexpr const char* Subtract = "VK_SUBTRACT";
    constexpr const char* Decimal = "VK_DECIMAL";
    constexpr const char* Divide = "VK_DIVIDE";
    constexpr const char* F1 = "VK_F1";
    constexpr const char* F2 = "VK_F2";
    constexpr const char* F3 = "VK_F3";
    constexpr const char* F4 = "VK_F4";
    constexpr const char* F5 = "VK_F5";
    constexpr const char* F6 = "VK_F6";
    constexpr const char* F7 = "VK_F7";
    constexpr const char* F8 = "VK_F8";
    constexpr const char* F9 = "VK_F9";
    constexpr const char* F10 = "VK_F10";
    constexpr const char* F11 = "VK_F11";
    constexpr const char* F12 = "VK_F12";
    constexpr const char* F13 = "VK_F13";
    constexpr const char* F14 = "VK_F14";
    constexpr const char* F15 = "VK_F15";
    constexpr const char* F16 = "VK_F16";
    constexpr const char* F17 = "VK_F17";
    constexpr const char* F18 = "VK_F18";
    constexpr const char* F19 = "VK_F19";
    constexpr const char* F20 = "VK_F20";
    constexpr const char* F21 = "VK_F21";
    constexpr const char* F22 = "VK_F22";
    constexpr const char* F23 = "VK_F23";
    constexpr const char* F24 = "VK_F24";
    constexpr const char* NumLock = "VK_NUMLOCK";
    constexpr const char* ScrollLock = "VK_SCROLL";
    constexpr const char* LShift = "VK_LSHIFT";
    constexpr const char* RShift = "VK_RSHIFT";
    constexpr const char* LControl = "VK_LCONTROL";
    constexpr const char* RControl = "VK_RCONTROL";
    constexpr const char* LMenu = "VK_LMENU";
    constexpr const char* RMenu = "VK_RMENU";
    constexpr const char* BrowserBack = "VK_BROWSER_BACK";
    constexpr const char* BrowserForward = "VK_BROWSER_FORWARD";
    constexpr const char* BrowserRefresh = "VK_BROWSER_REFRESH";
    constexpr const char* BrowserStop = "VK_BROWSER_STOP";
    constexpr const char* BrowserSearch = "VK_BROWSER_SEARCH";
    constexpr const char* BrowserFavorites = "VK_BROWSER_FAVORITES";
    constexpr const char* BrowserHome = "VK_BROWSER_HOME";
    constexpr const char* VolumeMute = "VK_VOLUME_MUTE";
    constexpr const char* VolumeDown = "VK_VOLUME_DOWN";
    constexpr const char* VolumeUp = "VK_VOLUME_UP";
    constexpr const char* MediaNextTrack = "VK_MEDIA_NEXT_TRACK";
    constexpr const char* MediaPrevTrack = "VK_MEDIA_PREV_TRACK";
    constexpr const char* MediaStop = "VK_MEDIA_STOP";
    constexpr const char* MediaPlayPause = "VK_MEDIA_PLAY_PAUSE";
    constexpr const char* LaunchMail = "VK_LAUNCH_MAIL";
    constexpr const char* LaunchMediaSelect = "VK_LAUNCH_MEDIA_SELECT";
    constexpr const char* LaunchApp1 = "VK_LAUNCH_APP1";
    constexpr const char* LaunchApp2 = "VK_LAUNCH_APP2";
    constexpr const char* OEM1 = "VK_OEM_1"; // For the US standard keyboard, the ';:' key
    constexpr const char* OEMPlus = "VK_OEM_PLUS"; // For any country/region, the '+' key
    constexpr const char* OEMComma = "VK_OEM_COMMA"; // For any country/region, the ',' key
    constexpr const char* OEMMinus = "VK_OEM_MINUS"; // For any country/region, the '-' key
    constexpr const char* OEMPeriod = "VK_OEM_PERIOD"; // For any country/region, the '.' key
    constexpr const char* OEM2 = "VK_OEM_2"; // For the US standard keyboard, the '/?' key
    constexpr const char* OEM3 = "VK_OEM_3"; // For the US standard keyboard, the '`~' key
    constexpr const char* OEM4 = "VK_OEM_4"; // For the US standard keyboard, the '[{' key
    constexpr const char* OEM5 = "VK_OEM_5"; // For the US standard keyboard, the '\|' key
    constexpr const char* OEM6 = "VK_OEM_6"; // For the US standard keyboard, the ']}' key
    constexpr const char* OEM7 = "VK_OEM_7"; // For the US standard keyboard, the 'single-quote/double-quote' key
    constexpr const char* OEM8 = "VK_OEM_8"; // Used for miscellaneous characters; it can vary by keyboard.
    constexpr const char* OEM102 = "VK_OEM_102"; // Either the angle bracket key or the backslash key on the RT 102-key keyboard
    constexpr const char* ProcessKey = "VK_PROCESSKEY"; // IME PROCESS key
    constexpr const char* Packet = "VK_PACKET"; // Used to pass Unicode characters as if they were keystrokes.
    constexpr const char* Attn = "VK_ATTN"; // Attn key
    constexpr const char* Crsel = "VK_CRSEL"; // CrSel key
    constexpr const char* Exsel = "VK_EXSEL"; // ExSel key
    constexpr const char* EraseEOF = "VK_EREOF"; // Erase EOF key
    constexpr const char* Play = "VK_PLAY"; // Play key
    constexpr const char* Zoom = "VK_ZOOM"; // Zoom key
    constexpr const char* PA1 = "VK_PA1"; // PA1 key
    constexpr const char* OEMClear = "VK_OEM_CLEAR"; // Clear key
}

#endif //INPUT_RECORDER_KEYS_HPP
